# Generated by Django 5.1.3 on 2024-11-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("product", "0002_alter_productorm_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartORM",
            fields=[
                (
                    "basetimeorm_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="base.basetimeorm",
                    ),
                ),
                (
                    "baseoidorm_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.baseoidorm",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EMTY CART", "Empty"),
                            ("NORMAL CART", "Normal"),
                            ("FULL CART", "Full"),
                        ],
                        default="EMTY CART",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CartORM",
            },
            bases=("base.baseoidorm", "base.basetimeorm"),
        ),
        migrations.CreateModel(
            name="CartItemORM",
            fields=[
                (
                    "baseoidorm_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.baseoidorm",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productorm",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="cart.cartorm",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CartItemORM",
            },
            bases=("base.baseoidorm",),
        ),
    ]
