# Generated by Django 5.1.3 on 2024-11-22 23:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartORM",
            fields=[
                (
                    "oid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EMTY CART", "Empty"),
                            ("NORMAL CART", "Normal"),
                            ("FULL CART", "Full"),
                        ],
                        default="EMTY CART",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CartORM",
            },
        ),
        migrations.CreateModel(
            name="CartItemORM",
            fields=[
                (
                    "oid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productorm",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="cart.cartorm",
                    ),
                ),
            ],
            options={
                "verbose_name": "CartItemORM",
            },
        ),
    ]
