# Generated by Django 5.1.3 on 2024-11-13 08:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartDto",
            fields=[
                (
                    "oid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Cart")),
                ("is_active", models.BooleanField(default=False)),
                ("products", models.ManyToManyField(to="product.productdto")),
            ],
            options={
                "verbose_name": "CartDto",
            },
        ),
    ]
