# Generated by Django 5.1.3 on 2024-11-24 02:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
        ("customer", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartorm",
            options={"verbose_name": "CartORM"},
        ),
        migrations.AddField(
            model_name="cartorm",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.customerorm",
            ),
        ),
        migrations.AddField(
            model_name="cartorm",
            name="items",
            field=models.ManyToManyField(
                through="cart.CartItemORM", to="product.productorm"
            ),
        ),
        migrations.AlterField(
            model_name="cartitemorm",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cart.cartorm"
            ),
        ),
        migrations.AlterField(
            model_name="cartitemorm",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.productorm"
            ),
        ),
        migrations.AlterField(
            model_name="cartitemorm",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cartorm",
            name="status",
            field=models.CharField(
                choices=[
                    ("EMPTY CART", "Empty"),
                    ("NORMAL CART", "Normal"),
                    ("FULL CART", "Full"),
                ],
                default="EMPTY CART",
                max_length=16,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitemorm",
            unique_together={("cart", "product")},
        ),
    ]
