# Generated by Django 5.1.3 on 2024-11-22 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitemorm",
            options={"verbose_name": "CartItemORM"},
        ),
    ]
