# Generated by Django 5.1.3 on 2024-11-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdto",
            name="name",
            field=models.CharField(default="Cart", editable=False),
        ),
    ]
