# Generated by Django 5.1.3 on 2024-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_cartdto_name"),
        ("product", "0002_productdto_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdto",
            name="products",
            field=models.ManyToManyField(default=None, to="product.productdto"),
        ),
    ]
