# Generated by Django 5.1.3 on 2024-11-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_alter_cartdto_products"),
        ("product", "0002_productdto_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdto",
            name="products",
            field=models.ManyToManyField(
                blank=True, default=None, to="product.productdto"
            ),
        ),
    ]
