# Generated by Django 5.1.3 on 2024-11-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_alter_cartdto_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartdto",
            name="status",
            field=models.CharField(
                choices=[("empty", "empty"), ("full", "full")], default="empty"
            ),
        ),
    ]
