# Generated by Django 5.1.3 on 2024-11-22 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BaseOidORM",
        ),
        migrations.DeleteModel(
            name="BaseTimeORM",
        ),
    ]
