version: "3.9"
services:
  redis:
    image: redis:latest 
    container_name: redis
    ports: 
      - "6379:6379"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data
    


