# Generated by Django 5.1.3 on 2024-11-23 13:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerORM",
            fields=[
                (
                    "oid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default=None, max_length=32, null=True
                    ),
                ),
                ("token", models.UUIDField(blank=True, default=None, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "CustomerORM",
            },
        ),
    ]
