# Generated by Django 5.1.3 on 2024-11-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorm',
            name='email',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='customerorm',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
