# Generated by Django 5.1.3 on 2024-11-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0003_alter_customerorm_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerorm",
            name="token",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
