# Generated by Django 5.1.3 on 2024-11-12 11:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductDto",
            fields=[
                (
                    "oid",
                    models.UUIDField(
                        default=uuid.UUID("89808f35-427a-45f0-ad40-5ccd521ebd12"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(max_length=1024)),
                ("price", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
