# Generated by Django 5.1.3 on 2024-11-20 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productorm",
            options={"verbose_name_plural": "ProductORM"},
        ),
    ]
