# Generated by Django 5.1.3 on 2024-11-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdto",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
