# Generated by Django 5.1.3 on 2024-11-13 05:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productdto",
            options={"verbose_name": "ProductDto"},
        ),
        migrations.AlterField(
            model_name="productdto",
            name="oid",
            field=models.UUIDField(
                default=uuid.UUID("f752c319-42fb-4a0b-a856-5ef541a75fc8"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
