# Generated by Django 5.1.3 on 2024-11-22 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_productorm_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productorm",
            options={"verbose_name": "ProductORM"},
        ),
    ]
